[package]
name = "monte-carlo-comparison"
version = "0.1.0"
authors = ["Phil Nadon <phil@nadon.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"rand" = "0.7"